[env:esp32s2mini]
platform = espressif32
board = lolin_s2_mini
framework = arduino
upload_port = COM6
monitor_speed = 115200
lib_deps = 
    bblanchon/ArduinoJson @ ^7.0.0
build_src_filter = +<main.cpp> +<music.cpp>

